apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: second-pod
  ports:
    - port: 8000 # Its possible to listen to a different port than the target. Just need to add targetPort with the pod port.
      targetPort: 80
